### ISSUE TITLE
SEC P256 K1 EC Math on Oasis Sapphire can done with less gas

### ISSUE THREAD

**Issue by CedarMist** [DAO-Decentralization/dark-dao#2]
https://github.com/DAO-Decentralization/dark-dao/blob/54ecef5ff0e7ac1b6d18b13e69a4587eb2f37fe6/contracts/elliptic-curve/EllipticCurve.sol#L89

This is available in [EthereumUtils.sol](https://github.com/oasisprotocol/sapphire-paratime/blob/main/contracts/contracts/EthereumUtils.sol), the `k256DeriveY` function uses the `bigmodexp` precompile rather than solidity implementatoin of `expmod`. It also includes 

----

https://github.com/DAO-Decentralization/dark-dao/blob/54ecef5ff0e7ac1b6d18b13e69a4587eb2f37fe6/contracts/misc/KeyCoupling.sol#L40

The `Sapphire.generateSigningKeyPair()` function is equivalent to multiplying base point by some scalar.

This would reduce the gas cost of the curve & public key related operations significantly vs their current implementation.

**Comment by jaa2** [comment]
Thank you for pointing this out! Using the Sapphire precompile reduces the cost of the `deriveY` operation by approximately 30,000 gas.
